#cloud-config
packages:
  - git
  - pciutils
  - unzip
  - wget
  - make
  - docker-ce-cli
  - haveged
  - docker-ce
  - containerd.io
  - htop
  - tree

yum_repos:
  epel-release:
    metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    name: Extra Packages for Enterprise Linux 8 - Release
  docker-ce-stable:
    baseurl: >
     https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    name: Docker CE Stable - Debuginfo $basearch

users:
  - name: sake
    groups: adm, wheel, systemd-journal
    homedir: /sake
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNh8QVIYdqgnPK1jS2slJ7Xmcz3eEfqGRaSKqKK3gSF poq@frugal
  - name: bento
    groups: adm, wheel, systemd-journal, bento-v2-dev-data, docker
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG2Un6lcY8cYVVhWguuduVMfi/C2vO0Uc3dVLXv4GRyoOyGP7JA60vJz6QC8QYBsL8cCg1lko05Lk1477yq1Mj5Wfg5E8iZ6T3MweHJ+ZLsRxOatxDO0GX3XTQk8Vd7HxYgclaRnSFwCJeL41euuMjTdapXUb0ycku6ipmGaxx2JupOE/KB8w8RjHxWX010FyR26NiPpALzCYzwALm+VaLZc+C6Io1LT1BNzr00hEVxMEyEjWQipaUTJKMdCxXtVNdnQieGtlGLw8U1uIarEHp/6eMt9/KEATX2CJhD8/hWJmKkfvaQUHNoU8c5z0mqNpraJAC6xWCdpbjUfE7O4c3 poq@moins
      - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAlDucgrcjWRl3fEGLSoRl7a2izErUP/BNw9/+HSTfZUPaYhHgK06jPjp7fZAnudf5+fUl75xDvdBb3jiA7EUBM1TxZCreI/ZUCTtYFqNCedYo8zyB+RuuQznoJkqJIn8u67yDewftP5jz3MKGIe0ErxdisL/405AC23Bw2UcsRC/5RSe+X3aUQFwU4VSrDjVGMGJUB5xOEnrmIeRz8HE390T1zdzCfhrRF5puk4u4h7LeYp7Uorb5S5E0dx3DklSkYP65s6toGpZBUkO3W/J4w/g9n0XPhbkiY6PHi320SpYir8RHZnY+FB+IsD1TITJ0r6pIEWLWFxNDB7GFt0PXKQ== ksenia
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvIJZT7+JT230zFqHDVNDrxHk78U/JP64w7wm94+Z7/Ce+TNlbEH7W3lQ5DzdzIQfum1Zu4jnkhHgDV6V+dFrD1tb5AmzSErkA1r3PZSzj0w3FHU5Z43341BiAuw9EVX8Qa8SrufUwTzUyL3U0Uc7SxuxCO1WZa8LH3ISL/72gfoerJ+2JxC8KaEyg3JpVrzFn9FFz0y9K/JVk3ZCuKf+pDX1Bp0mpU8W5KG+YUv9dg3OsTF1brywlq5qyDjBy0A0OeVyCLj/EhCEwmeBW0S/q9pa7thTNaLtTdVptefHBBYEx3lXHCE6jpDT9y2AUCV9o7K2sXRdBiG9O2hRNmaxxnhIN8SlCN3qMeLhZ2wRrCJ4Q7hWIUZBoSBGgAO3aw6juRO3920XpK8nkYKaMXfFfeN5p8gy5epGsuY2IplhJ7tUBie7uFtdfIbikYX6XCCFE79rpMgGjTOF/imeIFxcyBii7IdQV4vDdKdgWO1va54QDz1y7sQ/uL2msz8AkC6k= brennan@Wolfsbane
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCh74kWmrjV8UUfwHf/dGcKQ7SVhVGYHRJR9ufKUPdnd1Fd4CmmDJxrjHSmhzS7+ZWiyz2Ho8b2GG9AT0BwK0hrZIr7pwDAOGfHjnbL8LHF8EyxCSv0r2FyxxW6YvjsNt0Dt2c42Ehe4t+RnGXX8Koj2GW8WCRHWIEViDNFDC0tuVlzfOr9IhYqdQhBSMusCh82oU5VxpqeeOuMgldfnyuyUuWoiDLExjjAmzMjFKFFs16pTuz3jt6AxZPFDD5ViUryVDqeOkjINHxGhKEwEu/y8wKucb5NXh+WNNQfdhNRSyBBG7kZv2SIrT4JOS7Uq72LDxsHkgRRo7GkC5iNN9VjYH1YiOemX4etUfEgHQiWH2eAFOABl1ZfTM6vHFTFtbAXtIgUOK7VkbmJxFpMCxun37dS1XIb990fXfli9A9pPSbGdBMAWNclOUKc/j+2ysVzboAhJeSYUW9u4gJT5v0uR/2zHQpCmYptWdUgO8UfjwLZoQRsmlhZBjXyuVUcNy9hQyvireA+ZvE6axwbhr0kS3M1ZSyh2tbaGtyu3txxlh0LdrPPP7Rg1d8E7C6NEwk7VNw/kBvGytcjbH0BRqBfurcbuZww9fwlCNNDVujUF0IB15MlUTSBuUPWzdmnC4BtTIcg+CKJ3ofy3JMpvUl4Sd408WmYd80idT8h2Et3iQ== Brownlee@heap

  - name: bento-data
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG2Un6lcY8cYVVhWguuduVMfi/C2vO0Uc3dVLXv4GRyoOyGP7JA60vJz6QC8QYBsL8cCg1lko05Lk1477yq1Mj5Wfg5E8iZ6T3MweHJ+ZLsRxOatxDO0GX3XTQk8Vd7HxYgclaRnSFwCJeL41euuMjTdapXUb0ycku6ipmGaxx2JupOE/KB8w8RjHxWX010FyR26NiPpALzCYzwALm+VaLZc+C6Io1LT1BNzr00hEVxMEyEjWQipaUTJKMdCxXtVNdnQieGtlGLw8U1uIarEHp/6eMt9/KEATX2CJhD8/hWJmKkfvaQUHNoU8c5z0mqNpraJAC6xWCdpbjUfE7O4c3 poq@moins

write_files:
  - content: PATH=$PATH:/usr/local/bin
    path: /etc/profile.d/sh.local
    permissions: "0644"

runcmd:
  - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod 755 /usr/local/bin/docker-compose
  - mkdir -p /data /var/lib/docker
  - parted /dev/vdb --script  mktable gpt
  - parted /dev/vdc --script  mktable gpt
  - parted /dev/vdb --script  mkpart primary  xfs 0% 100%
  - parted /dev/vdc --script  mkpart primary  xfs 0% 100%
  - mkfs.xfs /dev/vdc1
  - mkfs.xfs /dev/vdb1
  - echo "/dev/vdc1                /var/lib/docker       xfs     defaults        0 0" >> /etc/fstab
  - echo "/dev/vdb1                /data                 xfs     defaults        0 0" >> /etc/fstab
  - mount -a
  - chown  bento-v2:bento-v2 /data/
  - restorecon -R sake
     - "(echo -e '\nHostKeyAlgorithms ssh-rsa\n' >> /etc/ssh/sshd_config && systemctl restart sshd)"
  - yum upgrade -y
  - systemctl disable kdump
  - sed -i 's/crashkernel=auto/crashkernel=no/' /etc/default/grub
  - sed -i 's/GRUB_CMDLINE_LINUX="[^"]*/& nouveau.modeset=0 rd.driver.blacklist=nouveau/' /etc/default/grub
  - grub2-mkconfig -o /boot/grub2/grub.cfg
  - chmod 755 $(ls /usr/share/doc/rsync*/support/rrsync)
  - sudo ln -s $(ls /usr/share/doc/rsync*/support/rrsync) /usr/bin/rrsync
  - yum groupinstall -y 'Development Tools'
  - systemctl enable docker && systemctl start docker

disable_ec2_metadata: false
timezone: "UTC"
fqdn: bqc19
output: { all: "| tee -a /var/log/cloud-init-bento-config.log" }
