#cloud-config
packages:
  - git
  - vim
  - pciutils
  - unzip
  - wget
  - make
  - docker-ce-cli
  - haveged
  - docker-ce
  - containerd.io
  - docker-compose-plugin
  - htop
  - tree
  - cronie-noanacron
  # Required to build python 3.10
  - gcc
  - openssl-devel
  - bzip2-devel
  - libffi-devel 
  - zlib-devel
  - sqlite-devel  # specific to RHEL 9

package_update: true
package_upgrade: true
package_reboot_if_required: true

yum_repos:
  epel-release:
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    name: Extra Packages for Enterprise Linux 9 - Release
  docker-ce-stable:
    baseurl: >
     https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg
    name: Docker CE Stable - Debuginfo $basearch

# ADD PUBLIC SSH KEYS HERE
users:
  - name: sake
    groups: adm, wheel, systemd-journal
    homedir: /sake
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNh8QVIYdqgnPK1jS2slJ7Xmcz3eEfqGRaSKqKK3gSF poq@frugal
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxum9RRpQUxPaSL5FJP/bXM0P4vs23EuMkJoXvA5TV6 victor.rocheleau@mcgill.ca
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPjXNvynxihSsSiEQYK2wfSNWA6SdUFFylOx1CZUPXCu victor.rocheleau@mcgill.ca
  - name: bento
    groups: adm, wheel, systemd-journal, bento-data, docker
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNh8QVIYdqgnPK1jS2slJ7Xmcz3eEfqGRaSKqKK3gSF poq@frugal
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLBYtBhlkV3kSQniu1GZh/ISylNakoAo2710T11n/puDRZoRwEoyf2q95fDo086vP/Q8930+4ppDW0h0P6KIChB5o0TUBPW5jZ73buJlGyvJ0O2YIjegZzeRgp6ak691+InQyt0+a4q1zMidw9+LOWJErQzWTIY9lSeL07XeGM3XjAmlpaQCKSScgZEacOb+VJCgqQTcIb8uaRihwc+7agh4BONYOg8ov1n30lsC906V+O/aqJ9k8rKMP6tKx2SmIRbNdowN+8I4HMcF7sPFslSGjhbL6N/4yA3a4BO0Qk+BhgifRu1jiZnP08wZNwNGV2o4gibjN1tmTOkhykugke9WfYJavrZw4KY92sMANFBG29E9Dq1zg6xTPOzcmAxAdOHn85jAETqxsffzjv6+VWWURNRPlYVtF8vmqlUkqupbQtDyV3/RIwzbwJXGbezRV6UkAgDec2z8wgIJ1D1gGlzx7LmOwpLwgWwOk0V7XWb1fYUK/xfrhglBPZsXSiUEc= gordonkrieger@marigold
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCUjfzvcyZYmG/9U2lrOptQdtC5BTMU5zyUidx4+YEL3Ejfy4qi452WsWRJHb6LjnpCiW8dNH7VkD9Mn/SXuG2q5JjFnwclLx8OfM4HrJHK8j0xvzBOHIne28pfthQK41IFzPlGT30nE4LV89aNGqW2S+tfV8dOT9x9AdfjpxdU6d8HCjXBzqOopn+KdT/d9isUMzgTcTu8kaI4xZ8D0arO7UlrsXsLRF9e7Tf4l8S1bnV0HzFUxluoA5kUu9vVxSOcxbsQmGz6g/beOMfbi/M/qwf1JU5peNHZBrNfAYpIc2lAlRIoGkzV3URWC8BgOwZkWspJwQvldPH05g0lf2pnz8xxtmriTfMyW/nne26dvk0bzpNRB0PBU0QdjgMZSSaGnHnpk8oeYPGQesFEbwD6L7huwEN8q5ewoYPGPM0SKZzR848IGP498afZEPoOGt9eHq1q8nB4ugI0RYa/ZSv7Ri+RA68rSVVt1LPz0ZoLuVX9XHeleoKJ9ST6lr/wzDMZtjKSlSulUCDQ//DDCUBzXxZRK87AU3jPpxd5foJfhq2diN10QhfQjjTokKSK6McpuXE3qcW9sWX8xrZH0aMHyNi98l7XtPGs8z674lJF113jVDuhnOVRGxUIpSGLE6bsfihtElmvdrRgQtvGWU1kPh8m+tBk6rvILt0niJFb0Q== dbujold@xerces
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC2aCUNqdojLbc1QDkTU+Y0uyNhOa/8xuR5n2fvUUyT9kLNrkUV2r4mIPT49GRFqo0RVfsHmvvHfSUGTnQUCGd3QTc9FTBxeEKs38hHlFaasvbLy+blf7aTXTi9Y453UH71pLhs4DrwnGKSm9W9eiRawMCBwXSj5QlrVsltCtoyQtjmxJIQ6cwZgpFMu5kRveJI5Sln9Q3x6YXhcHKAQo8WYg06t6Wr7fyjyhClPO+H55Lkwo1BJoJtNWcjsMbzwXc4VxsCKHO5U+jWvfhUSgVqCr7kogXx/inEMKQZdkKkcV3k6FukkTYW3Ik5w+f+mBKaPB9w7mEPNTz2MfmNz11ZC3QGAJP24izBl5KaPG3E9U0kZR63qXVHv2DdxJu4E1yBm3Idgpke3ar685R/rO53SXGd0OpyZI4WBi2SamxythmLyX0lcgdoNgJiRcBQdNxiqXjscvDCFo5fkuFck5uanUHBT8TfjXhxkYEtNQdylEMxuOW2ItOXyPfv4+wwb60HDC2fYEE7n/x43yWDbClm6uDRkxMwEmZ86yeBlcpCDLFWmp0CE/fg2zyPC0/aQG5GJ1Lmn4nb//bHDMx66VBQTVfISVybrMMbCgR82PXineEpaRRF5ZNxeI1wChbIlLThsaiv6nlrQFt6rqPz7H6hq0IUpccN5vKAWcHmVoRO4Q== dbujold@xerces
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnK0KLHVvXtqefoSvDgG5vk1kuNv/nN8qD1SQwHW6wv/wEX+yLD/p8VcCft7zmdExzNlpWfi+2bsvRl03pJXDZYyPJ7mcANUO5uoa/RQhC3INARscKlTm/E9XYl3DVytnhnWdUglUUPzvN8H1F7MDaf8EoIqWvrQcb7YZlU5EplJjZvolsn6dg1WuuvGdYZyWkHUYCGyHy8tSheMo6qWYdevmIWulYn5vJ1/FTmoaVWp38Vs+5DyFRAQCU9FgMaQiDIWnZWM6mPlMp5TxGT3tiMc0cV6gyW5gi4FpbFEreqX8smRlkSVXaXyS1VsCMhRefgKVBRp6wFyaD+RiCjfNNzVV9i1di8aR6K1LHZWcqBqQr7VDbgt7HNrlqAdSPLicqV5oaZ6DawGj4cjgmyYI0NWlgK3mithqB4Y1fWgtx1Zq7D2lad29p0xGQqCsbcsdlH97ODGggsvbMVHpW9vWUgXTJypm1cHcnxrB3MRGT/5dtKRDLLgsWJHAQiUiAVG8= julianmhenao@gardenia
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD48mAvyJxYagSvdErTpgs9ZzF7oMyVPKG0MkNAKtqGBImfmPVRTyZYjZX6dBZC7HRTBrXCFOakxBN+U1ZnM9yLIvDhyGaLtMunj8BoluqRgd7+8VkWJWE08AbAEwDlomcibHaTRN7flWnPRz1udcmVu9bGqfk5v1bD1/hlUU3XhD/RsCvNH3Pnf4RWwm1jM6uCIq1kncOcwK15o27sE7FSLcw02jVbMlLs/bXANRum5FKsrvIKuGtdpGBmQ+MX+w3FKDWrc1gOiZD7LWuODeOxOb1llXPVF5OcSpjoRqieTawKsNSoa2D2NMkUtIlleRerZT3KXCBYnRtQxKgLz821 david.lougheed@gmail.com
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxum9RRpQUxPaSL5FJP/bXM0P4vs23EuMkJoXvA5TV6 victor.rocheleau@mcgill.ca
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPjXNvynxihSsSiEQYK2wfSNWA6SdUFFylOx1CZUPXCu victor.rocheleau@mcgill.ca
  - name: bento-data
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKNh8QVIYdqgnPK1jS2slJ7Xmcz3eEfqGRaSKqKK3gSF poq@frugal
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxum9RRpQUxPaSL5FJP/bXM0P4vs23EuMkJoXvA5TV6 victor.rocheleau@mcgill.ca
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPjXNvynxihSsSiEQYK2wfSNWA6SdUFFylOx1CZUPXCu victor.rocheleau@mcgill.ca

write_files:
  - content: PATH=$PATH:/usr/local/bin
    path: /etc/profile.d/sh.local
    permissions: "0644"


device_aliases:
  data_disk: /dev/vdb
  docker_disk: /dev/vdc
  app_disk: /dev/vdd

disk_setup:
  data_disk:
    table_type: gpt
    layout: true
    overwrite: false
  app_disk:
    table_type: gpt
    layout: true
    overwrite: true
  docker_disk:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - label: data_fs
    device: /dev/vdb1
    filesystem: xfs
  - label: docker_fs
    device: /dev/vdc1
    filesystem: xfs
  - label: app_fs
    device: /dev/vdd1
    filesystem: xfs

mounts:
  - [ /dev/vdc1, /var/lib/docker, xfs, "defaults,nofail", "0", "0"]
  - [ /dev/vdb1, /data,           xfs, "defaults,nofail", "0", "0"]
  - [ /dev/vdd1, /app,            xfs, "defaults,nofail", "0", "0"]


runcmd:
  # Init /data /app /var/lib/docker mounted directories
  - mkdir -p /data /var/lib/docker /app
  # Set directories owner/group
  - chown -R bento:bento-data /data/
  - chown -R bento:bento /app
  # Allow bento-data to read/write on /data
  - chmod g+rw /data
  # SSH setup
  - restorecon -R sake
     - "(echo -e '\nHostKeyAlgorithms ssh-rsa\n' >> /etc/ssh/sshd_config && systemctl restart sshd)"
  - dnf upgrade -y
  - systemctl disable kdump
  # Grub setup
  - sed -i 's/crashkernel=auto/crashkernel=no/' /etc/default/grub
  - sed -i 's/GRUB_CMDLINE_LINUX="[^"]*/& nouveau.modeset=0 rd.driver.blacklist=nouveau/' /etc/default/grub
  - grub2-mkconfig -o /boot/grub2/grub.cfg
  # rrsync setup
  - chmod 755 $(ls /usr/share/doc/rsync*/support/rrsync)
  - sudo ln -s $(ls /usr/share/doc/rsync*/support/rrsync) /usr/bin/rrsync
  # Dev Tools
  - dnf groupinstall -y 'Development Tools'
  # Docker
  - systemctl enable docker && systemctl start docker
  # Python 3.10 source install to /opt
  # Use a valid Python version available on https://www.python.org/ftp/python/
  # Refer to the Bento repo for the python version requirement https://github.com/bento-platform/bento
  - wget https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tar.xz
  - tar -xf Python-3.10.13.tar.xz -C /opt/ && rm Python-3.10.13.tar.xz && cd /opt/Python-3.10.13
  - ./configure --enable-optimizations && make -j 2 && make altinstall


disable_ec2_metadata: false
timezone: "UTC"
fqdn: ${BENTO_HOSTNAME}
output: { all: "| tee -a /var/log/cloud-init-bento-config.log" }
